-- phpMyAdmin SQL Dump
-- version 4.1.14.8
-- http://www.phpmyadmin.net
--
-- Client :  db701137160.db.1and1.com
-- Généré le :  Jeu 05 Octobre 2017 à 12:10
-- Version du serveur :  5.5.57-0+deb7u1-log
-- Version de PHP :  5.4.45-0+deb7u11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `db701137160`
--

-- --------------------------------------------------------

--
-- Structure de la table `Post`
--

CREATE TABLE IF NOT EXISTS `Post` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `standFirst` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `content` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `lastModif` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=22 ;

--
-- Contenu de la table `Post`
--

INSERT INTO `Post` (`id`, `title`, `author`, `standFirst`, `content`, `lastModif`) VALUES
(1, 'Choisir sa formation', 'Carole Duval', 'Programmateur d''applications ou Data-scientist ? Et au début fut une question ...', 'Dans ma tête, c''était parfaitement clair : je voulais apprendre à programmer. Je voulais fournir des outils aux professionnels pour leur faciliter le quotidien, pour les aider à faire évoluer leurs entreprises, pour les faire entrer dans le siècle numérique.\r\nVoilà, définir mon projet professionnel, c''était facile ... Reste à trouver la formation adéquate.\r\nSauf que ... un parcours de data-scientist ? où se mélangent allègrement langage informatique et manipulation de super base de données ! ah, je n’y avais pas réfléchi avant mais j’aime bien l’idée ! et puis, c’est très recherchée comme compétence.\r\nPas si simple de choisir finalement … Développeur d’applications Back End ? Front End ? Data-Scientist ?\r\nFace à ce dilemme, j’ai fait appel à un outil de base : le liste de + et de -. Basique mais efficace !\r\nJe veux pouvoir manipuler les données à l’aide de langages informatiques. Exit le Front End !\r\nReste quand même 2 alternatives très séduisantes, je regarde les prérequis et … je me souviens …\r\nJE N’AIME PAS les calculs statistiques avancés, je me rappelle qu’en année de maitrise, j’avais souffert le martyr sur cet UV.\r\nEt bien finalement, je reviens à ma première idée : développeur d’applications Back End. Lettre de motivation en poche, je me rends à mon entretien Pôle Emploi, il m’a fallut moins de 5 minutes pour convaincre le conseiller en face de moi. 2 semaines plus tard, j’attaque le parcours Open Class Rooms de Développeur en Application PHP/Symfony et c’est parti pour 12 mois de formation en e-learning !\r\n', '2017-05-14 16:32:00'),
(2, 'P1 : Un début tranquille', 'Carole Duval', 'Un premier module d''apprentissage ... sur l''apprentissage !', 'Dans ce projet, on me demande de retravailler mon projet professionnel en le mettant à jour avec la formation que j’ai débutée : Quels sont mes objectifs ? Quel type d’investissement j’envisage ?\r\nJ’ai déjà réfléchi à cela avant de m’inscrire à cette formation :\r\nJe remets donc par écrit ce que j’ai décidé : réaliser cette formation de développeur en moins d’un an et trouver rapidement après un emploi de développeur en application dans ma région ou en télétravail.\r\nJe construis conjointement mon planning, tenant compte de ma capacité de travail (évaluée à 30 h/sem) et de mes disponibilités (j’allège en heures les semaines où mes enfants sont en vacances).  J’arrive à une fin estimée à fin mars 2018, soit 11 mois.\r\nParallèlement, je dois mettre à jour mon CV et mon compte LinkedIn.\r\nCe projet de mise en bouche est réalisé en 2 jours.', '2017-05-15 10:12:00'),
(3, 'P2 : Prendre en main WordPress', 'Carole DUVAL', 'Exercice de style : Adapter un thème WordPress au besoin client  ', 'Décrypter le besoin client fait partie de mes compétences professionnelles (Qualité oblige !). Donc à priori, pas de difficultés particulières sur ce projet.\r\nPrendre l’outil WordPress en main est chose relativement aisée. Choisir le bon thème et les bonnes extensions a été par contre un peu plus délicat, tant l’offre est riche. Après avoir hésité entre plusieurs thèmes, j’ai finalement choisi Llorix One Little, un thème sobre et riche en fonctionnalités. Ce thème initialement dédié au blog s’est révélé très pratique : chaque chalet a été traité comme un post et il a été facile de produire 2 pages « à vendre » et « à louer » en leur affectant la catégorie correspondante.\r\nJ’ai pu y ajouter des extensions pour notamment implanter des diaporamas (pratiques pour présenter les chalets), un formulaire de contact et un plan.\r\nJ’aurais aimé aller plus loin dans la personnalisation de ce site mais il était encore trop tôt pour manipuler les fichiers php sauf pour l’ajout d’un fil d’Ariane. Même si cela paraît anodin, j’étais très fière d’avoir réussi cette manipulation (après tout, cela ne faisait que 3 semaines que j’avais commencé la formation).\r\nLa dernière partie technique, la mise en place d’une administration site, a été une simple formalité puisqu’intégralement pris en charge par WordPress.\r\nEnfin la rédaction de la documentation m’a ramené une nouvelle fois à mon métier d’origine à travers la rédaction de documentation, sujet que je maitrise plutôt bien.\r\nLe résultat est visible à l''adresse suivante : http://chaletsetcaviar.carole-duval.fr/', '2017-06-12 10:00:00'),
(4, 'P3 : Analyser les besoins d''un client', 'Carole DUVAL', 'Comment construire un projet à partir des éléments fournis par le client', 'Le client en question monte son "Festival de Films de plein air". Disposant de peu de moyens, il a besoin d''un site internet pour communiquer sur l''évènement : programmation, actualités et pour enregistrer les réservations bien que l''accès soit gratuit.\r\nPour ce projet, j''ai décidé de travailler à nouveau avec WordPress : en effet, cela permet de fournir un site personnalisé, opérationnel rapidement, et facile à entretenir, idéal pour un client qui a peu de moyens financiers et sans doute humains.\r\n\r\nj''ai choisi le thème Event, parfaitement adapté à cette activité.\r\nJ''ai ajouté Events Manager un module de gestion d''évènements et de réservations ainsi que plusieurs petits plug-ins de communication : Newsletter, SuperSocializer (qui insère des icônes vers les réseaux sociaux) ainsi que l''essentiel Contact Form 7 pour un formulaire de contact efficace.\r\nLe résultat est visible à l''adresse : http://films-de-plein-air.carole-duval.fr/.\r\n', '2017-07-07 11:07:00'),
(5, 'P4 : Concevoir une solution technique', 'Carole DUVAL', 'Modéliser un projet avec UML', 'Express Food est une entreprise de traiteur livrant à domicile. Son créneau : la livraison à vélo en moins de 20 minutes après la validation de la commande.\r\nIl faut concevoir la base de données d''Express Food qui permettra de stocker notamment les listes de clients, des différents plats du jour, des livreurs, avec leur statut (libre, en cours de livraison) et leur position et bien sur la liste des commandes passées.\r\nL''exercice consiste donc à concevoir la base de données via un schéma UML, de le traduire en MPD (Modèle Physique de Données) et de construire la base de données correspondante dans MySQL.\r\nAprès une légère angoisse de la page blanche au début, le projet s''est bien déroulé, sans difficultés particulières.\r\n', '2017-09-05 15:31:00'),
(6, 'P5 : Créer un blog en PHP', 'Carole DUVAL', 'Si vous lisez ce texte, c''est que ce projet est en bonne voie ....', 'Les choses se corsent dans ce 5ème projet : cette fois, je code pour de vrai de A à Z.\r\nMais d''abord, préparation du projet avec la modélisation UML : \r\nDiagramme de contexte : sans difficultés \r\nDiagramme de packages : sans difficultés\r\nDiagrammes des cas d''utilisation : sans difficultés\r\nCas d''utilisation internes : une fois bien renseignée sur le contenu de chaque rubrique, pas de difficultés particulières.\r\nDiagramme de classes : sans aucune expérience pratique de construction intégrale de site, je me suis inspirée des cours que j''ai suivi. J''ai donc travaillé sur les classes suivantes : post, postmanager, contrôleur(s), router, mail. Certaines classes ont été faciles à définir dès le début (post, mail, post manager), les autres ont évoluées en cours d''avancement pour coller à la réalité du travail effectué.\r\nDiagrammes de séquence : comme pour les diagrammes de classes, il y en avait des faciles à concevoir dès le début et d''autres qui se sont faits en cours de route (même si ce n''est pas bien, je le sais mais je plaide le manque d''expérience pour cette fois-ci).\r\nPour la partie code, évidemment, il y a eu des passages difficiles, cela me semble normal, j''ai du tomber dans tous les pièges des débutants (la syntaxe, les fins de boucle mal placées, un argument manquant dans une fonction, ....).\r\nAu final, ce site fonctionne bien, j''espère qu''il vous plait !', '2017-10-05 11:04:00'),
(7, 'Parcours OC : les compétences acquises', 'Carole DUVAL', 'Point sur les compétences acquises au fil de la formation', 'P5 :\r\n- Créer une page web permettant de recueillir les informations saisies par un internaute \r\n- Analyser un cahier des charges \r\n- Créer et maintenir l’architecture technique du site \r\n- Choisir une solution technique adaptée parmi les solutions existantes si cela est pertinent \r\n- Conceptualiser l''ensemble de son application en décrivant sa structure (Entités / Domain Objects) \r\n- Estimer une tâche et tenir les délais \r\n- Gérer ses données avec une base de données \r\n- Rédiger les spécifications détaillées du projet\r\n\r\nP4 :\r\n- Concevoir l’architecture technique d’une application à l’aide de diagrammes UML \r\n- Implémenter le schéma de données dans la base \r\n- Réaliser un schéma de conception de la base de données de l’application \r\n\r\nP3 :\r\n- Rédiger les spécifications détaillées du projet \r\n- Lister les fonctionnalités demandées par un client \r\n- Choisir une solution technique adaptée parmi les solutions existantes si cela est pertinent \r\n- Analyser un cahier des charges \r\n\r\nP2 : \r\n- Adapter un thème Wordpress pour respecter les exigences du client\r\n- Rédiger une documentation à l''intention d''utilisateurs non spécialistes\r\n- Sélectionner un thème Wordpress adapté aux besoins du client\r\n\r\nP1 :\r\n- Créer et mettre à jour son CV\r\n- Fixer des objectifs clairs', '2017-10-05 11:14:00');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
